# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agc < Formula
  desc "Clean up IDE caches and build artifacts (Antigravity, Flutter, Xcode, Android)"
  homepage "https://github.com/iml1s/antigravity-cleaner"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/iml1s/antigravity-cleaner/releases/download/v0.1.0/antigravity-cleaner_Darwin_x86_64.tar.gz"
      sha256 "0452ffdfb355d497076edf143d0f4389b50069b4e01d680d90ab694416db7ab4"

      def install
        bin.install "agc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/iml1s/antigravity-cleaner/releases/download/v0.1.0/antigravity-cleaner_Darwin_arm64.tar.gz"
      sha256 "c95d2bef9515b6af6c34f4c62798a1cc6a4330e66b6fecb9fa6afd1e066f414a"

      def install
        bin.install "agc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/iml1s/antigravity-cleaner/releases/download/v0.1.0/antigravity-cleaner_Linux_x86_64.tar.gz"
      sha256 "fd254505b747fa8900766bc7db463d2186f703d6cacdb0b5508a433872d407f0"
      def install
        bin.install "agc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/iml1s/antigravity-cleaner/releases/download/v0.1.0/antigravity-cleaner_Linux_arm64.tar.gz"
      sha256 "d30fa4c962ce5d71a4267c72260e9a3aad506d1bd511db113211a54e8f2699a4"
      def install
        bin.install "agc"
      end
    end
  end

  test do
    system "#{bin}/agc", "--version"
  end
end
